"""SP4 T1 — the pure renderer + fence parser (H-S4-1/2/4).

The renderer is str → str: no filesystem I/O, no journal, engine-free.
The fence parser is matched-pair-or-raise. The generator imports only
tpcore.engine_profile + stdlib.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))
# Evict a non-package ``ops`` (scripts/ops.py) cached by an earlier test in
# full-suite collection order, so ``import ops.*`` resolves the package —
# the scripts/ops.py vs ops/ collision that bit SP2-T9.
for _m in [m for m in list(sys.modules) if m == "ops" or m.startswith("ops.")]:
    if not hasattr(sys.modules[_m], "__path__"):
        del sys.modules[_m]

import scripts.gen_engine_manifest as gm  # noqa: E402

ROSTER = ("reversion", "vector", "momentum", "sentinel", "canary",
          "catalyst")
ARCHIVED = ("sigma",)

OPEN = ("# >>> engine-manifest:smoke-loop (generated by "
        "scripts/gen_engine_manifest.py — edit the SoT, not this) >>>")
CLOSE = "# <<< engine-manifest:smoke-loop <<<"


# pytest-xdist: pin this ops-shadow module to one worker so its
# sys.modules['ops'] / scripts/ops.py loading stays single-process
# (the ops/ package-shadow is a single-process invariant). P1.3.
pytestmark = pytest.mark.xdist_group("ops_shadow")


def test_renderer_is_pure_no_filesystem_io():
    """render_* perform no filesystem I/O — the source of every render
    helper contains no open(/.write_text/.write_bytes/os.write, and a
    call returns a pure transformed string (the original string is not
    mutated, nothing is written)."""
    src = gm.__file__
    body = Path(src).read_text()
    # Split: the ONLY intentional writer is the _cli_write function.
    forbidden = ("open(", ".write_text(", ".write_bytes(", "os.write(")
    # Locate the render functions' source via inspect — assert none of
    # them reference a write primitive.
    import inspect
    for fn in (gm.render_region, gm.render_all, gm.divergences):
        fsrc = inspect.getsource(fn)
        for tok in forbidden:
            assert tok not in fsrc, (
                f"{fn.__name__} contains forbidden fs primitive {tok!r} "
                f"— the renderer must be pure str→str (H-S4-1)")
    text = f"before\n{OPEN}\nstale\n{CLOSE}\nafter\n"
    out = gm.render_region(text, "smoke-loop", ROSTER, ARCHIVED)
    assert isinstance(out, str)
    assert text == f"before\n{OPEN}\nstale\n{CLOSE}\nafter\n", (
        "render_region mutated its input string — must be pure")
    assert "before\n" in out and "after\n" in out
    del body  # the module-source read is for the structural assert only


def test_unmatched_sentinel_raises():
    text = f"x\n{OPEN}\nbody\n"  # open present, close absent
    with pytest.raises(gm.ManifestFenceError):
        gm.render_region(text, "smoke-loop", ROSTER, ARCHIVED)


def test_duplicate_sentinel_raises():
    text = f"{OPEN}\na\n{CLOSE}\n{OPEN}\nb\n{CLOSE}\n"
    with pytest.raises(gm.ManifestFenceError):
        gm.render_region(text, "smoke-loop", ROSTER, ARCHIVED)


def test_missing_close_sentinel_raises():
    text = f"{OPEN}\nbody-no-close\n"
    with pytest.raises(gm.ManifestFenceError):
        gm.render_region(text, "smoke-loop", ROSTER, ARCHIVED)


def test_text_outside_fence_is_never_touched():
    pre = "LIVE-PRE-1\nLIVE-PRE-2\n"
    post = "LIVE-POST-1\nLIVE-POST-2\n"
    text = f"{pre}{OPEN}\nWILL-BE-REPLACED\n{CLOSE}\n{post}"
    out = gm.render_region(text, "smoke-loop", ROSTER, ARCHIVED)
    assert out.startswith(pre), "bytes before the fence were altered"
    assert out.endswith(post), "bytes after the fence were altered"
    assert "WILL-BE-REPLACED" not in out, "fence body not regenerated"


def test_generator_imports_no_engine():
    """H-S4-4: importing the generator in a fresh interpreter pulls in
    NO engine package and NO ops.* — pure SoT reads only."""
    code = (
        "import sys; import scripts.gen_engine_manifest;"
        "bad=[m for m in sys.modules if m.split('.')[0] in "
        "{'reversion','vector','momentum','sentinel','canary','ops'}];"
        "print(';'.join(bad))"
    )
    res = subprocess.run(  # noqa: S603
        [sys.executable, "-c", code],
        cwd=str(REPO_ROOT), capture_output=True, text=True, check=True)
    assert res.stdout.strip() == "", (
        f"generator eager-imported forbidden modules: {res.stdout!r}")


import ast  # noqa: E402
import tomllib  # noqa: E402

_SHADOWS = (
    "scripts/run_smoke_test.sh",
    "scripts/run_all_engines.sh",
    "ops/platform_pipeline.py",
    "pyproject.toml",
)


@pytest.mark.parametrize("rel", _SHADOWS)
def test_generator_is_idempotent(rel):
    """H-S4-3: render_all is a fixed point — render_all(render_all(x))
    == render_all(x) for every shadow file as committed."""
    text = (REPO_ROOT / rel).read_text()
    once = gm.render_all(text, rel, ROSTER, ARCHIVED)
    twice = gm.render_all(once, rel, ROSTER, ARCHIVED)
    assert twice == once, f"{rel}: render_all is not idempotent"


@pytest.mark.parametrize("rel", _SHADOWS)
def test_check_clean_after_write(rel):
    """H-S4-3: the committed shadow is already byte-identical to its
    own regeneration (a clean checkout never needs a regen ritual)."""
    text = (REPO_ROOT / rel).read_text()
    assert gm.render_all(text, rel, ROSTER, ARCHIVED) == text, (
        f"{rel}: committed bytes != regeneration — run the generator")


def test_smoke_sh_still_parses():
    res = subprocess.run(  # noqa: S603
        ["bash", "-n", "scripts/run_smoke_test.sh"],
        cwd=str(REPO_ROOT), capture_output=True, text=True)
    assert res.returncode == 0, (
        f"run_smoke_test.sh failed bash -n post-fence:\n{res.stderr}")


def test_run_all_engines_sh_still_parses():
    res = subprocess.run(  # noqa: S603
        ["bash", "-n", "scripts/run_all_engines.sh"],
        cwd=str(REPO_ROOT), capture_output=True, text=True)
    assert res.returncode == 0, (
        f"run_all_engines.sh failed bash -n post-fence:\n{res.stderr}")


def test_pyproject_still_valid_toml():
    pp = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text())
    testpaths = set(pp["tool"]["pytest"]["ini_options"]["testpaths"])
    includes = set(pp["tool"]["setuptools"]["packages"]["find"]["include"])
    for e in ROSTER:
        assert f"{e}/tests" in testpaths, f"{e}/tests missing"
        assert f"{e}*" in includes, f"{e}* missing"
    # the hand-owned non-engine rows survive outside the fence:
    assert "tpcore/tests" in testpaths
    assert "tpcore*" in includes


def test_platform_pipeline_docstring_still_valid():
    src = (REPO_ROOT / "ops" / "platform_pipeline.py").read_text()
    mod = ast.parse(src)
    doc = ast.get_docstring(mod)
    assert doc is not None, "platform_pipeline lost its module docstring"
    assert " → ".join(ROSTER) in doc, (
        "the regenerated dispatch-order line is absent from the docstring")
