"""The engine non-Python shadow-manifest generator (SP4 §10).

Closes the SP1 H-B6 carry-forward: every non-Python shadow of the
roster SoT (the run_smoke_test.sh step-3 loop + its docstring, the
run_all_engines.sh dispatch-order line, the platform_pipeline.py
docstring, the pyproject testpaths/include engine rows) is regenerated
FROM tpcore.engine_profile and a silent drift is ungameable.

Three callers, ONE writer-per-context (H-S4-1):
  * CI ``--check``  — regenerate in memory, diff vs disk, READ-ONLY.
  * ``--write``     — idempotent in-place regen (operator/regen tool).
  * the SP3 executor (ops/engine_sdlc/planner.py, T5) — journals OLD
    bytes, then writes the renderer's returned NEW text; rollback
    restores OLD. The renderer NEVER writes / NEVER journals.

Imports tpcore.engine_profile + stdlib ONLY — no engine, no ops
(tpcore∌engine layering, H-S4-4).
"""
from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

from tpcore.engine_profile import archived_engines, roster_for_dispatch

REPO_ROOT = Path(__file__).resolve().parents[1]

_ENGINE_TOKEN = re.compile(r"^[a-z0-9_]+$")

_SENTINEL_NOTE = ("generated by scripts/gen_engine_manifest.py — "
                  "edit the SoT, not this")


class ManifestFenceError(RuntimeError):
    """A fenced region's sentinel pair is missing / unmatched /
    duplicated / crossed — fail LOUD, never silently no-op (H-S4-2)."""

    def __init__(self, file: str, region: str, reason: str) -> None:
        super().__init__(f"{file}: region {region!r}: {reason}")
        self.file = file
        self.region = region
        self.reason = reason


def _open_marker(region: str) -> str:
    return f"# >>> engine-manifest:{region} ({_SENTINEL_NOTE}) >>>"


def _close_marker(region: str) -> str:
    return f"# <<< engine-manifest:{region} <<<"


def _assert_roster_safe(roster: tuple[str, ...]) -> None:
    for tok in roster:
        if not _ENGINE_TOKEN.match(tok):
            raise ManifestFenceError(
                "<roster>", "<all>",
                f"roster token {tok!r} is not ^[a-z0-9_]+$ — refusing "
                f"to emit unsafe bash/TOML/docstring")


def _region_body(region: str, roster: tuple[str, ...],
                 archived: tuple[str, ...]) -> str:
    """The SoT-derived body emitted BETWEEN the sentinel markers
    (exclusive). Each body ends with exactly one trailing newline so
    the close marker sits on its own line."""
    _assert_roster_safe(roster)
    space = " ".join(roster)
    arrow = " → ".join(roster)
    comma = ", ".join(roster)
    if region == "smoke-loop":
        return f"for engine in {space}; do\n"
    if region == "smoke-doc":
        return (f"#   3. Per-engine scheduler dry-run (no orders "
                f"submitted): {comma}\n#      (Sigma archived "
                f"2026-05-16).\n")
    if region == "all-engines-doc":
        return f"# Engines dispatched: {arrow}.\n"
    if region == "pipeline-doc":
        return (f"    2. ``scripts/run_all_engines.sh`` — runs "
                f"{arrow} schedulers back-to-back (Sigma\n"
                f"       archived 2026-05-16). Each engine handles\n"
                f"       its own market-closed / no-rebalance / "
                f"no-candidates gating.\n")
    if region == "pyproject-testpaths":
        return "".join(f'    "{e}/tests",\n' for e in roster)
    if region == "pyproject-include":
        return "".join(f'    "{e}*",\n' for e in roster)
    raise ManifestFenceError("<unknown>", region, "unknown region id")


def render_region(file_text: str, region: str,
                  roster: tuple[str, ...],
                  archived: tuple[str, ...]) -> str:
    """Pure str → str. Replace ONLY the bytes strictly between the one
    matched ``>>> engine-manifest:<region> >>>`` /
    ``<<< engine-manifest:<region> <<<`` pair. Zero / >1 / crossed /
    missing-close ⇒ ManifestFenceError (LOUD). No filesystem I/O, no
    journal (H-S4-1/2)."""
    om = _open_marker(region)
    cm = _close_marker(region)
    n_open = file_text.count(om)
    n_close = file_text.count(cm)
    if n_open == 0 and n_close == 0:
        raise ManifestFenceError(
            "<text>", region, "no sentinel pair present")
    if n_open != 1 or n_close != 1:
        raise ManifestFenceError(
            "<text>", region,
            f"expected exactly one open and one close marker, "
            f"found open={n_open} close={n_close}")
    oi = file_text.index(om)
    ci = file_text.index(cm)
    if ci < oi:
        raise ManifestFenceError(
            "<text>", region, "close marker precedes open marker")
    # the body is everything after the open marker line through the
    # newline immediately before the close marker line.
    after_open = file_text.index("\n", oi) + 1
    before_close = file_text.rindex("\n", 0, ci) + 1
    if before_close < after_open:
        raise ManifestFenceError(
            "<text>", region, "crossed/empty fence span")
    body = _region_body(region, roster, archived)
    return file_text[:after_open] + body + file_text[before_close:]


# Which region ids live in which shadow file (relative to REPO_ROOT).
_FILE_REGIONS: dict[str, tuple[str, ...]] = {
    "scripts/run_smoke_test.sh": ("smoke-doc", "smoke-loop"),
    "scripts/run_all_engines.sh": ("all-engines-doc",),
    "ops/platform_pipeline.py": ("pipeline-doc",),
    "pyproject.toml": ("pyproject-testpaths", "pyproject-include"),
}


def render_all(file_text: str, file_rel: str,
               roster: tuple[str, ...],
               archived: tuple[str, ...]) -> str:
    """Pure str → str. Regenerate EVERY region declared for
    ``file_rel`` in ``file_text`` (idempotent fixed point — H-S4-3).
    No filesystem I/O."""
    out = file_text
    for region in _FILE_REGIONS.get(file_rel, ()):
        out = render_region(out, region, roster, archived)
    return out


def divergences(repo_root: Path | None = None) -> str | None:
    """Pure, in-process, READ-ONLY: regenerate every fenced region of
    every shadow file in memory and diff vs the bytes on disk. Returns
    a unified diff naming the drifted file/region, or None if every
    region is byte-identical. The T4 clockwork delegation + the T3
    --check share this (one mechanism)."""
    root = repo_root or REPO_ROOT
    roster = roster_for_dispatch()
    archived = archived_engines()
    chunks: list[str] = []
    for rel in _FILE_REGIONS:
        p = root / rel
        on_disk = p.read_text()
        regenerated = render_all(on_disk, rel, roster, archived)
        if regenerated != on_disk:
            chunks.append("".join(difflib.unified_diff(
                on_disk.splitlines(keepends=True),
                regenerated.splitlines(keepends=True),
                fromfile=f"{rel} (on disk)",
                tofile=f"{rel} (regenerated from SoT)")))
    return "".join(chunks) if chunks else None


def _cli_write(repo_root: Path) -> int:
    """The ONE intentional file writer (the operator/idempotent-regen
    tool — NOT the transaction path; the SP3 executor has its own
    journal+write). Rewrites every fenced region in place."""
    roster = roster_for_dispatch()
    archived = archived_engines()
    for rel in _FILE_REGIONS:
        p = repo_root / rel
        cur = p.read_text()
        new = render_all(cur, rel, roster, archived)
        if new != cur:
            p.write_text(new)
    return 0


def _cli_check(repo_root: Path) -> int:
    diff = divergences(repo_root)
    if diff is None:
        return 0
    sys.stderr.write(
        "engine shadow-manifest DRIFT — a roster/SoT change did not "
        "regenerate the shadows. Run `python scripts/gen_engine_"
        "manifest.py` and commit.\n")
    sys.stderr.write(diff)
    return 1


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="gen_engine_manifest",
        description="Regenerate the non-Python engine shadows from the "
                    "tpcore.engine_profile SoT (SP4 §10).")
    g = p.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true",
                   help="READ-ONLY: exit non-zero + unified diff on "
                        "any drift (the CI-divergence gate).")
    g.add_argument("--write", action="store_true",
                   help="(default) rewrite every fenced region in "
                        "place; idempotent.")
    ns = p.parse_args(argv)
    if ns.check:
        return _cli_check(REPO_ROOT)
    return _cli_write(REPO_ROOT)


if __name__ == "__main__":  # pragma: no cover - CLI shim
    raise SystemExit(main())
