#!/usr/bin/env bash
# Thin caller of ops.engine_dispatch (profile-gated; per-engine gating
# in Python, not bash). Use after run_data_operations.sh has confirmed
# clean data.
#
# This is the operator's daily-trade trigger: data fresh ⇒ dispatcher
# runs each engine that tpcore.engine_profile.should_fire +
# capital_gate clears ⇒ orders submitted to Alpaca paper ⇒
# trade_monitor (running separately) watches fills.
# >>> engine-manifest:all-engines-doc (generated by scripts/gen_engine_manifest.py — edit the SoT, not this) >>>
# Engines dispatched: reversion → vector → momentum → sentinel → canary → catalyst.
# <<< engine-manifest:all-engines-doc <<<
#
# Per-engine gating (validation freshness, should_fire, capital_gate)
# now lives in ops/engine_dispatch.py — NOT a global all-or-nothing
# bash preamble, which is exactly what capital_gate was built to
# refine away.
#
# NOTE: each scheduler is one-shot. The trade_monitor must already be
# running as a daemon (or `python -m tpcore.trade_monitor` in another
# terminal) for the Tier 2 cascade to fire.
#
# A manual single-engine --force run is the direct
# `python -m <engine>.scheduler --force` path, NOT this script.
set -uo pipefail
cd "$(dirname "$0")/.."

set -a
# shellcheck disable=SC1091
source .env
set +a

echo "▶ engine dispatch (profile-gated)"
DATABASE_URL="$DATABASE_URL_IPV4" exec .venv/bin/python -m ops.engine_dispatch "$@"
