"""End-to-end synthetic test of the AAR persistence pipeline against the live DB.

Proves that ``tpcore.aar.writer.AARWriter`` writes ``AfterActionReport``
rows to ``platform.aar_events`` correctly without waiting for an engine to
actually fill a real trade. Useful when the trading-side prerequisites
aren't met (no live broker, paper engines haven't fired, etc.) but the
operator still needs to verify the AAR plumbing works.

Behaviour
---------
1. Build a clearly-synthetic ``AfterActionReport`` with ``engine =
   'synthetic_test'`` and a UUID trade_id (so it cannot collide with any
   real engine row, past or future).
2. Open an asyncpg pool, hand it to ``AARWriter``, and call
   ``write_aar(aar)``. Assert it returns ``True`` (new row written).
3. Read the row back from ``platform.aar_events`` and compare every field
   against the original — proves serialization + deserialization are
   round-trip clean.
4. Call ``write_aar(aar)`` again with the SAME object. Assert it returns
   ``False`` (idempotent skip via the ``UNIQUE (engine, trade_id)``
   constraint + ``ON CONFLICT DO NOTHING``).
5. **Always** ``DELETE`` the synthetic row in a ``finally`` block, even
   on failure, so the production table never accumulates harness data.

Usage
-----
::

    python scripts/test_aar_pipeline.py

Reads ``DATABASE_URL`` (or ``DATABASE_URL_IPV4`` for the local Supabase
pooler) from the environment.
"""
from __future__ import annotations

import asyncio
import json
import os
import sys
import uuid
from datetime import UTC, datetime
from decimal import Decimal

import structlog

from tpcore.aar.models import AfterActionReport, ExitReason
from tpcore.aar.writer import AARWriter
from tpcore.db import build_asyncpg_pool

logger = structlog.get_logger(__name__)

SYNTHETIC_ENGINE = "synthetic_test"


def _make_synthetic_aar() -> AfterActionReport:
    now = datetime.now(UTC)
    return AfterActionReport(
        engine=SYNTHETIC_ENGINE,
        trade_id=f"aar_pipeline_test_{uuid.uuid4()}",
        ticker="ZZZZ",  # not a real ticker
        entry_ts=now,
        exit_ts=now,
        entry_price=Decimal("100.00"),
        exit_price=Decimal("101.50"),
        qty=Decimal("1"),
        confidence_at_entry=Decimal("0.75"),
        confidence_at_exit=Decimal("0.80"),
        sizing_pct_of_engine_equity=Decimal("0.05"),
        pnl_gross=Decimal("1.50"),
        pnl_net=Decimal("1.45"),
        fees=Decimal("0.05"),
        slippage_bps=Decimal("2.0"),
        regime_tags=["synthetic", "harness_test"],
        exit_reason=ExitReason.OTHER,
        rule_compliance=True,
        notes="Generated by scripts/test_aar_pipeline.py — safe to ignore.",
    )


async def _delete_synthetic(pool, engine: str, trade_id: str) -> int:
    sql = "DELETE FROM platform.aar_events WHERE engine=$1 AND trade_id=$2 RETURNING id"
    async with pool.acquire() as conn:
        rows = await conn.fetch(sql, engine, trade_id)
    return len(rows)


async def _read_back(pool, engine: str, trade_id: str) -> dict | None:
    sql = """
        SELECT engine, trade_id, ticker, aar_data, recorded_at
          FROM platform.aar_events
         WHERE engine = $1 AND trade_id = $2
    """
    async with pool.acquire() as conn:
        row = await conn.fetchrow(sql, engine, trade_id)
    if row is None:
        return None
    return {
        "engine": row["engine"],
        "trade_id": row["trade_id"],
        "ticker": row["ticker"],
        "aar_data": json.loads(row["aar_data"]),
        "recorded_at": row["recorded_at"],
    }


async def _amain() -> int:
    db_url = os.getenv("DATABASE_URL") or os.getenv("DATABASE_URL_IPV4")
    if not db_url:
        print("DATABASE_URL not set", file=sys.stderr)
        return 2

    aar = _make_synthetic_aar()
    pool = await build_asyncpg_pool(db_url)
    writer = AARWriter(pool)

    print(f"step 1: synthetic AAR built — engine={aar.engine!r} trade_id={aar.trade_id!r}")

    try:
        # 2. First write — should INSERT and return True.
        wrote_first = await writer.write_aar(aar)
        if not wrote_first:
            print("FAIL: first write_aar returned False (expected True for a new row)")
            return 1
        print("step 2: first write_aar → True (new row inserted) ✓")

        # 3. Read back and compare every field.
        roundtrip = await _read_back(pool, aar.engine, aar.trade_id)
        if roundtrip is None:
            print("FAIL: row not found after insert")
            return 1
        # The row's aar_data is the JSON-serialized model; compare to the model's own dump.
        original_dump = json.loads(aar.model_dump_json())
        if roundtrip["aar_data"] != original_dump:
            print("FAIL: round-trip mismatch")
            print(f"  written : {original_dump}")
            print(f"  read    : {roundtrip['aar_data']}")
            return 1
        if roundtrip["engine"] != aar.engine or roundtrip["trade_id"] != aar.trade_id:
            print(
                f"FAIL: top-level columns mismatch "
                f"(engine={roundtrip['engine']!r}, trade_id={roundtrip['trade_id']!r})"
            )
            return 1
        if roundtrip["ticker"] != aar.ticker:
            print(f"FAIL: ticker mismatch (got {roundtrip['ticker']!r})")
            return 1
        print("step 3: round-trip read matched original AAR exactly ✓")

        # 4. Second write — should be a no-op (UNIQUE constraint hit, ON CONFLICT DO NOTHING).
        wrote_second = await writer.write_aar(aar)
        if wrote_second:
            print("FAIL: second write_aar returned True (expected False — idempotent skip)")
            return 1
        print("step 4: second write_aar → False (idempotent skip) ✓")

        # 5. Verify still exactly one row (not two).
        async with pool.acquire() as conn:
            count = await conn.fetchval(
                "SELECT COUNT(*) FROM platform.aar_events WHERE engine=$1 AND trade_id=$2",
                aar.engine,
                aar.trade_id,
            )
        if count != 1:
            print(f"FAIL: expected exactly 1 row after idempotent re-write, found {count}")
            return 1
        print("step 5: row count is exactly 1 after duplicate write ✓")

        print()
        print("PASS: AAR pipeline end-to-end against live DB.")
        print(
            "  → write_aar inserts, round-trip reads match, "
            "duplicate writes are silently dropped by the unique constraint."
        )
        return 0
    finally:
        deleted = await _delete_synthetic(pool, aar.engine, aar.trade_id)
        print(f"cleanup: deleted {deleted} synthetic row(s) from platform.aar_events")
        await pool.close()


def main() -> int:
    return asyncio.run(_amain())


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
