"""Anthropic Managed-Agents IDs — generated by ``scripts/anthropic_agent_provision.py``.

Constants module. The finder SDK reads ``EDGE_FINDER_AGENT_ID`` +
``EDGE_FINDER_ENVIRONMENT_ID`` to attach sessions to the right
managed agent + environment. The ``EDGE_FINDER_MEMSTORE_ID`` is
the operator's pre-seeded finder memstore from the 2026-05-22
Anthropic memory-store handoff.

DO NOT hand-edit. Regenerate via ``python -m
scripts.anthropic_agent_provision``.
"""
from __future__ import annotations

EDGE_FINDER_AGENT_ID: str = "agent_01VqnLyKyottRyEy5zHaE2E5"
EDGE_FINDER_ENVIRONMENT_ID: str = "env_01Ckg2jNzwPVQZEtbMeR1XQa"
EDGE_FINDER_MEMSTORE_ID: str = "memstore_01MzLun3AfRf2viPmDqJvsWi"
"""Operator-seeded finder memstore — 2026-05-22 handoff.

Contains: /agent-context/, /cross-agent/dev-to-finder/,
/outcomes/, /prior-emissions/ (6 emissions from v2.0 gate pilot).
The finder reads these on startup + writes /sessions/<run_id>.md
at completion per persona §11."""

PROVISIONED_PERSONA_SHA256: str = "1f9cd272035ff12e279307e8c16132c39c3dc015f72cd615d899fb3ac1393cca"
"""SHA256 of the persona text written to the agent's ``system``
field at provision time. The finder SDK asserts this matches
``tpcore.lab.llm_finder.PERSONA_SHA256`` at runtime — mismatch
means the persona file was edited without re-provisioning."""

MANAGED_AGENTS_BETA: str = "managed-agents-2026-04-01"
"""Required beta header on every Sessions API call."""

__all__ = [
    "EDGE_FINDER_AGENT_ID",
    "EDGE_FINDER_ENVIRONMENT_ID",
    "EDGE_FINDER_MEMSTORE_ID",
    "MANAGED_AGENTS_BETA",
    "PROVISIONED_PERSONA_SHA256",
]
