"""Anthropic Managed-Agents IDs for the LLM-AAR critic — generated by
``scripts/anthropic_aar_critic_provision.py``.

Constants module. The critic SDK reads ``AAR_CRITIC_AGENT_ID`` +
``AAR_CRITIC_ENVIRONMENT_ID`` + ``AAR_CRITIC_MEMSTORE_ID`` to attach
sessions to the right Managed Agent + environment + dedicated AAR
memstore.

The finder memstore ID is ALSO carried here so the AAR critic can copy
findings into the finder's memstore at /aar-findings/<engine>/ (per
spec §4.3 + §7).

DO NOT hand-edit. Regenerate via:
    python -m scripts.anthropic_aar_critic_provision
"""
from __future__ import annotations

AAR_CRITIC_AGENT_ID: str = "agent_01QWApPtdsg35VyJFe7wyZE6"
"""Set by scripts/anthropic_aar_critic_provision.py."""

AAR_CRITIC_ENVIRONMENT_ID: str = "env_01NnpRKdmEu15xHLdY3yYqdH"
"""Set by scripts/anthropic_aar_critic_provision.py."""

AAR_CRITIC_MEMSTORE_ID: str = "memstore_01UQaUeYoL4kZwTF722CiLpg"
"""Created by scripts/anthropic_aar_critic_provision.py with
name='aar-llm-critic-context'. Per spec §4.1."""

FINDER_MEMSTORE_ID: str = "memstore_01MzLun3AfRf2viPmDqJvsWi"
"""The Task #25 finder memstore — operator-seeded 2026-05-22 handoff.
AAR findings are curated-copied here at /aar-findings/<engine>/<finding_id>.md
per spec §4.3 + §7. Stable; do not regenerate."""

PROVISIONED_PERSONA_SHA256: str = "bc403a1647248e0c421833d29d827a5566fa908b5ec4d83c5aceb9cfb9263388"
"""SHA256 of the persona text written to the agent's ``system`` field at
provision time. The critic SDK warns on drift (defense-in-depth)."""

MANAGED_AGENTS_BETA: str = "managed-agents-2026-04-01"
"""Required beta header on every Sessions API call. Per Anthropic
managed-agents API current docs (2026-05-22 via context7 MCP)."""


__all__ = [
    "AAR_CRITIC_AGENT_ID",
    "AAR_CRITIC_ENVIRONMENT_ID",
    "AAR_CRITIC_MEMSTORE_ID",
    "FINDER_MEMSTORE_ID",
    "MANAGED_AGENTS_BETA",
    "PROVISIONED_PERSONA_SHA256",
]
